### PR TITLE
Multi NavLayout #5

### LINKED ISSUE #5: NavBar in Start (Home Site)
-replace text with images (martin will create the images)

(important, NavBar looks different than NavBar in Location/Character/Episodes/Games)

### PR DESCRIPTION
**Pull request by mpagels**
Finally commit my Multi NavLayout #5 

- StartPage has 4 big Buttons
- All other pages have Nav at bottom fixed
- Change Background Image like we discussed

### CODE REVIEW

**Comment by mpagels** [comment]
And I see that I really have to deal with the subject of rebase, asap ;-)

**Comment by maxbischof** [comment]
Directorys have uppercase names

**Comment by annaleaschroeder** [comment]
For consistency's sake, we could consider including the StartPage into a separate file in the pages-directory.

**Comment by maxbischof** [comment]
Bildschirmfoto 2020-08-20 um 12 42 31
Component has plural name and file singular

**Comment by maxbischof** [comment]
`import Navigation from './components/Navigation'`can be removed in app.js

**Comment by mpagels** [comment]
> Bildschirmfoto 2020-08-20 um 12 42 31
> Component has plural name and file singular

good catch. I will fix the name.

**Comment by mpagels** [comment]
> Directorys have uppercase names

I don´t know why this happened. I changed the directory to lowerCase locally, because the pull with the directory changes did not work ;-(

**Comment by maxbischof** [comment]
As discussed:
* Delete Layouts
* Add setheadline in startpagenav

**Review by annidrumm — COMMENTED** [review]
Start page looks great! Especially the buttons with the images!

Some small input from my side.
- by scrolling down and up again the `Nav`disappears at the bottom.
- Background Image in `Characters`, `Episodes`and `Locations` looks a bit blurry.  Better shown in `Home` and `Dead or Alive`.
- I would suggest that we implement images in the Navigation for a better UX and cleaner style.

**Comment by mpagels** [comment]
> put from my side.
> 
>     * by scrolling down and up again the `Nav`disappears at the bottom.
> 
>     * Background Image in `Characters`, `Episodes`and `Locations` looks a bit blurry.  Better shown in `Home` and `Dead or Alive`.
> 
>     * I would suggest that we implement images in the Navigation for a better UX and cleaner style.

this should be new issues for when we have more time on this topics ;-)

**Pull request merged**
